### ISSUE TITLE
Be able to apply duplicated field group to pages and posts aswell.

### ISSUE THREAD

**Issue by FranzSkuffka** [Hube2/acf-options-page-adder#11]
I am using the custom fields to allow the user to configure module slots, like this i can only apply them to an options page and not to unique pages.

It's not urgent but a thing that this tool would greatly profit from.

**Comment by Hube2** [comment]
An interesting idea, being able to duplicate field groups to anywhere. Should not be a stretch. I'm currently swamped on another project but I will think about this and look at the possibility.

**Comment by FranzSkuffka** [comment]
Hmm i just realised that that defeats the purpose..
Instead one should use the flexible layout field from acf i guess.

**Comment by Hube2** [comment]
While the flexible content/layout field is useful, I actually like the idea of duplicating a field group on a post or even a term, or even having a "Field Group Repeater" which is what flexible content is all about. I'm still going to give it some thought and will likely play around with the idea when I have some time to see what it could offer that a flexible content field doesn't. 

Honestly I'm not extremely familiar with the what flexible content offers, so I'll likely start by learning that better. I have a project starting in the near future where using the flexible content will play a major role so I'll be thinking of this while I'm working on that.

**Comment by FranzSkuffka** [comment]
It basically exactly did for me what i was looking for here.
Basically, it gives you field groups, repeated, ordered and typed.

As it is a list, it will give you automatic prefixing, as in terms of numbering. You can filter by which field group ("layout") you used in a certain "slot" which you could call typing, as in terms of oop. In addition to that you may give a minimum and maximum number of slots being filled.
