### ISSUE TITLE
Be able to add custom html outside of the table view?

### ISSUE THREAD

**Issue by jjrohrer** [Hube2/acf-options-page-adder#13]
I want to add some custom html at the top or bottom of the table view page.  The html should be dynamic.  I simply can't figure what to hook into or where to inject my own code.  Any suggestions - is it possible?

Background: I've got a fork of acf-options-page-adder going that is facilitating saving and loading json in support of making a distributable plugin (that still requires acf-options-page-adder and act).  It is mostly working but has lots of personal code, so really isn't suitable to distribute (ironically) - still mostly in development phase.
I love your plugin - btw.

**Comment by jjrohrer** [comment]
I'm sure I'm missing something simple
![options_pages_ _et-appchase-003__test__ _wordpress](https://cloud.githubusercontent.com/assets/69016/7656526/f6fdbd8c-faf8-11e4-878f-9b9bdd8bf324.jpg)

**Comment by jjrohrer** [comment]
If it is technically painful, I suppose it I could make my own sub-menu item.

**Comment by Hube2** [comment]
I'm glad you like the plugin.

As far as the page that you're showing, it's just a standard WP post admin page. The options pages are stored as a custom post type. 

This page uses /wp-admin/edit.php. I just did a quick look into this file and it doesn't appear that WP supplies any hooks for added content to these places.

The only thing that's really available to hook into is to add additional columns to the table and I know there is a way to add filters, but I've never done that.

**Comment by Hube2** [comment]
Actually, I did just find this, which appears to allow adding content before and after the standard content on the page. 

http://wordpress.stackexchange.com/questions/140319/add-content-before-after-admin-post-wp-list-table
