### ISSUE TITLE
Field Groups not appearing on options pages

### ISSUE THREAD

**Issue by thisischrisj** [Hube2/acf-options-page-adder#15]
I'm sure this is just user error but I can't get the Fieldset Duplicator to work and was hoping you'd be able to shed some light.

The option pages already exist (coded up in functions.php as opposed to through the plugin) and the fieldset exists (currently autoloads on selected pages using the Page Template == xxx rule). Here's a screenshot of my Fieldset Duplicator set-up:

<img width="1020" alt="screen shot 2015-10-19 at 10 27 36" src="https://cloud.githubusercontent.com/assets/1276268/10574149/151f3ccc-764c-11e5-927d-f3af214536c7.png">

However, the fieldset doesn't appear on the two option pages. Is there anything obvious that I'm missing?

WP: 4.2.2
ACF Pro: 5.2.8
ACF Options Adder: 3.0.0

**Comment by Hube2** [comment]
I will check this out. There have been quite a few changes to ACF since I created the duplicator add on for this plugin and there might be a problem. It's been a while since I've used it myself.

**Comment by Hube2** [comment]
Solved this, ACF sets a cache to field groups and I have to delete that cache before adding the new field groups for some reason or they don't get registered properly and the key for the cache value was changed. Should be working now.
