### ISSUE TITLE
Suggestion: Stylized toggles

### ISSUE THREAD

**Issue by pedro-mendonca** [Hube2/acf-options-page-adder#33]
Hi,
I suggest to use the new Stylized UI toggles of ACF Pro in _Redirect_ and _Autoload_ optons radio buttons.
I've already tested it, you can check it out here https://github.com/pedro-mendonca/acf-options-page-adder/commit/15831b198aa423332fb2ce47c7b53438e7aa8bb3.

**Comment by Hube2** [comment]
I will look into this and make the needed changes to the field group. This was build a long time ago before that option was available and I didn't even think about it.

**Comment by pedro-mendonca** [comment]
My doubt is if the choice values are the same.
In my local testing it works ok. And looks good :)

**Comment by Hube2** [comment]
Yes, I see what you mean. It appears that I used a radio button field for this so that it was more user friendly than a true/false field checkbox. I'll need to dig into it further to figure out what else I'd need to change. It appears that I am saving either a 1 or 0 just like an acf true/false field, but I'll have to test that to be sure it doesn't break anything.

**Comment by Hube2** [comment]
Turns out it was completely safe since I was using 0/1 as values. I also change the choices from true/false to yes/no added some more missing __() calls

**Comment by Hube2** [comment]
:) I see you forked again between my updates, sorry if my commits are making you re-fork. There are a few plugins here that I don't let sit when there is interest and I can easily make the changes, this is one of them.

**Comment by pedro-mendonca** [comment]
Great 👍 
I'm just syncing to update the translation with the new strings and checkout your implementation of true_false fields :)

**Comment by pedro-mendonca** [comment]
You left this one behind :D
https://github.com/pedro-mendonca/acf-options-page-adder/commit/1ad46b582028f4c604092d42cfdcffd9e88b3a5b

**Comment by pedro-mendonca** [comment]
After a more broad review and understanding of the context of 'Post XX'; 'This Post (XX)', etc, just pushed a final PR.
