### ISSUE TITLE
i18n of ACF button on Options Page

### ISSUE THREAD

**Issue by pedro-mendonca** [Hube2/acf-options-page-adder#35]
The 'Update' button on the Options Page is probably from ACF core and isn't getting translated.

**Comment by Hube2** [comment]
I think I saw something about an update button not being translated on the forum, but the update button should be the standard WP post update button.

**Comment by pedro-mendonca** [comment]
Ok, so probably is a ACF core issue, I found it here:
https://support.advancedcustomfields.com/forums/topic/submit-button-in-option-page-is-not-translated/
I'm closing the issue here.
Thanks
