### ISSUE TITLE
ACP 5.6.4 Compatibility

### ISSUE THREAD

**Issue by wglassbrook** [Hube2/acf-options-page-adder#49]
Updating to latest ACF 5.6.4 causes Options Page Adder to include additional meta boxes to every edit page.

"Duplicator Settings" meta boxes as they appear on adding/editing posts or pages

<img width="1602" alt="add_new_post_wordpress" src="https://user-images.githubusercontent.com/3577550/32058479-1321f9b4-ba38-11e7-9d1a-33d2c53d342b.png">

"Options Page Details" meta boxes as they appear on adding/editing posts or pages

<img width="1600" alt="add_new_post_wordpress" src="https://user-images.githubusercontent.com/3577550/32058511-26b00ebc-ba38-11e7-9c7a-6f4ec6eaf47f.png">

Additional meta boxes also appear on any taxonomy editors.

Only current workaround is to fall back to ACF 5.6.3 or disable Options Page Adder.

**Comment by Hube2** [comment]
That's interesting.

I don't know what you have going on here, but the field set duplicator was removed in version 3.6.0 and I'm not seeing any of this weirdness on my test site using WP 4.8.2, and ACF 5.6.4. 

What version of this plugin are you using?

**Comment by Hube2** [comment]
If you're seeing the field set duplicator then you have a pretty old version of this plugin running. I removed github updater support for this plugin when I published it to the WP repo.

You should probably uninstall the version of this plugin that you're using and install the new version from here https://wordpress.org/plugins/options-page-admin-for-acf/. The version here on github exactly matches the version available from the WP repo.

**Comment by wglassbrook** [comment]
That was it. I was still on 2.2.0 (on MANY different sites) expecting GitHub Updater to take care of it. Great plugin and thanks for the quick replies!
