### ISSUE TITLE
Updating ACF plugin now breaks the WP back end due to a post_type filter in acf-options-page-adder

### ISSUE THREAD

**Issue by toshex** [Hube2/acf-options-page-adder#50]
Hi, I recently experienced some issues with this plugin and contacted ACF support about it, they were able to track the issues back to this plugin. This is their response, hope it helps:

> You have a plugin called 'acf-options-page-adder-master' which is adding a lot of ACF custom functionality.
> This plugin is modifying the location rule for 'post_type' and returning -1 (I'm not sure what the purpose of this is).
> 
> This is the issue. If this filter is removed, or if the -1 is changed to false (as it should be a boolean), the issue is solved.
> I have commented out this filter on line 67 of your acf-options-page-adder-master main file.
> 
> This issue has been there all along, however, a recent change to the ACF plugin has allowed the issue to surface.
> I hope you are able to find a solution for your custom code.

Can this be addressed and resolved?

**Comment by toshex** [comment]
Just noticed I am using an old version of the plugin directly from git and it's not updating since I guess there's a different branch that's auto-updating on the WP plugins repo.

**Comment by Hube2** [comment]
Let me know if it helps using the new version.

If it doesn't, let me know what the original issue was
